# 📝 실습 문제 풀기
이 노트북은 배운 내용을 복습하고 연습하는 공간이에요.
문제를 읽고 코드를 직접 작성해보세요! 화이팅! 💪


- **[1] Numpy: ndarray 기초**
    
    ### **[실습] 다양한 방법으로 배열 생성**
    
    <aside>
    ❓
    
    NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.
    
    1. 크기가 4x3인 모든 값이 0인 배열
    2. 크기가 3x3인 모든 값이 1인 배열
    3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
    4. 0과 1 사이의 4개의 등간격 값을 가진 배열
    5. *크기가 2x2인 정규 분포로 구성된 배열*
    </aside>

In [2]:
import numpy as np
# 1. 크기가 4x3인 모든 값이 0인 배열
arr = np.zeros((4, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# 2. 크기가 3x3인 모든 값이 1인 배열
arr = np.ones((3, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# 3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
arr = np.arange(0, 21, 5)
print(arr)

[ 0  5 10 15 20]


In [7]:
# 4. 0과 1 사이의 4개의 등간격 값을 가진 배열
arr = np.linspace(0, 1, 4)
print(arr)

[0.         0.33333333 0.66666667 1.        ]


In [8]:
# 5. *크기가 2x2인 정규 분포로 구성된 배열*
arr = np.random.randn(2, 2)
print(arr)

[[ 0.5984248  -0.34326755]
 [ 1.82827741  0.03910164]]


- **[2] Numpy: ndarray 인덱싱 및 슬라이싱**

### **[실습 1] 인덱싱과 슬라이싱**

<aside>
❓

1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서 2번째 행, 3번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출
</aside>

```
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
```

In [17]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  # 배열 생성
# 1. 배열 `arr`에서 1번째 열만 추출
print(arr[:, 1])

[20 50 80]


In [18]:
# 2. 배열 `arr`에서 2번째 행, 3번째 열의 값을 출력
print(arr[1, 2])

60


In [19]:
# 3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출
print(arr[0:2, 0:2])

[[10 20]
 [40 50]]


### [**실습 2] 팬시 인덱싱과 불리언 인덱싱**

<aside>
❓

아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출
</aside>

```
arr = np.array([10, 20, 30, 40, 50, 60, 70])
```

In [23]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])      # 배열 생성
# 1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
idx = [0, 2, 4]
print(arr[idx])

[10 30 50]


In [24]:
# 2. 배열의 값 중 50보다 큰 값만 추출
print(arr[arr > 50])

[60 70]


### [**실습 3] 제품 판매 데이터 분석**

<aside>
❓

어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.
</aside>

```
sales = np.array([[120, 150, 100],
                    [80, 90, 110],
                    [200, 180, 220],
                    [50, 45, 70],
                    [300, 320, 310]])
```

In [ ]:
sales = np.array([[120, 150, 100],                # 배열 생성
                    [80, 90, 110],
                    [200, 180, 220],
                    [50, 45, 70],
                    [300, 320, 310]])
# 1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
print(sales >= 200)
print(sales[sales >= 200])

[[False False False]
 [False False False]
 [ True False  True]
 [False False False]
 [ True  True  True]]
[200 220 300 320 310]


In [30]:
# 2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
print(sales[:, 2] <= 100)
print(sales[sales[:, 2] <= 100, 0:2])

[ True False False  True False]
[[120 150]
 [ 50  45]]


In [33]:
# 3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.
print(sales[:, 1] >= 150)
print(sales[sales[:, 1] >= 150])

[ True False  True False  True]
[[120 150 100]
 [200 180 220]
 [300 320 310]]


- **[3] Numpy: 연산**
    
    ### **[실습] 데이터를 기반으로 배열 연산 수행**
    
    <aside>
    ❓
    
    다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.
    
    1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
    2. 과일별 평균 판매량을 구하세요.
    
    - **데이터**:
        - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
        - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)
    </aside>

In [37]:
import numpy as np

sales_q1 = np.array([200, 340, 150, 400])         # 배열 생성
sales_q2 = np.array([220, 300, 180, 420])         # 배열 생성

total = sales_q1 + sales_q2
print(f"과일별 총 판매량 : {total}")

avg_sales = total/2
print(f"과일별 평균 판매량 : {avg_sales}")

과일별 총 판매량 : [420 640 330 820]
과일별 평균 판매량 : [210. 320. 165. 410.]


### **[실습 1] 기본 산술 연산**

<aside>
❓

다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

</aside>

In [38]:
arr1 = np.array([10, 20, 30, 40])                 # 배열 생성
arr2 = np.array([1, 2, 3, 4])                     # 배열 생성

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


### [**실습 2] Dot Product**

<aside>
❓

다음 두 배열 간의 내적 연산을 수행하세요.

</aside>

In [39]:
arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([4, 5, 6])                        # 배열 생성

print(np.dot(arr1, arr2))

32


### [**실습 3] 브로드캐스팅**

<aside>
❓

아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

</aside>

In [40]:
arr2d = np.array(                                 # 배열 생성
    [[1, 2, 3],
     [4, 5, 6]]
)
arr1d = np.array([10, 20, 30])                    # 배열 생성

print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


### **[실습 4] 비교 연산 및 집계 함수 사용**

<aside>
❓

1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.
</aside>

In [43]:
arr = np.array([10, 20, 30, 40, 50])              # 배열 생성

print(arr > 20)
print(arr[arr > 20])

print(f"합계 : {arr.sum()}")                        # 합계 계산
print(f"최대값 : {arr.max()}")
print(f"최소값 : {arr.min()}")
print(f"평균 : {arr.mean()}")                       # 평균 계산


[False False  True  True  True]
[30 40 50]
합계 : 150
최대값 : 50
최소값 : 10
평균 : 30.0


- **[4] Numpy: 통계**

### **[실습 1] 중심 경향 및 산포 측도 계산**

<aside>
❓

아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.

</aside>


In [45]:
!pip install scipy

   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   -------------- ------------------------- 13.9/38.6 MB 72.5 MB/s eta 0:00:01
   ------------------------ --------------- 23.3/38.6 MB 56.8 MB/s eta 0:00:01
   ---------------------------------------  38.5/38.6 MB 64.4 MB/s eta 0:00:01
   ---------------------------------------- 38.6/38.6 MB 54.5 MB/s  0:00:00


In [46]:
import numpy as np
from scipy import stats

arr = np.array([10, 20, 30, 30, 40, 50, 60])      # 배열 생성

print(np.mean(arr))
print(np.median(arr))
print(stats.mode(arr))
print(np.var(arr))
print(np.std(arr))
print(np.max(arr) - np.min(arr))

34.285714285714285
30.0
ModeResult(mode=np.int64(30), count=np.int64(2))
253.06122448979593
15.90789817951435
50


    ### [**실습 2] 정규분포와 균등분포의 난수 생성**
    
    <aside>
    ❓
    
    정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.
    
    1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
    2. 0과 1 사이의 균등분포 난수 1000개 생성
    </aside>

In [48]:
# 1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
arr = np.random.randn(1000)
print(np.mean(arr))
print(np.std(arr))

0.024165622963973767
1.0057198558067586


In [49]:
# 2. 0과 1 사이의 균등분포 난수 1000개 생성 (uniform)
uniform_arr = np.random.uniform(0, 1, 1000)
print(np.mean(uniform_arr), np.std(uniform_arr))

0.4993599016318147 0.2907876873031508


### [**실습 3] 평균 성적 구하기**

<aside>
❓

아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.

</aside>

In [50]:
# 학생별 과목 성적 데이터
scores_math =    [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

score = np.array([scores_math, scores_english, scores_science])  # 배열 생성
print(score)

[[88 92 76 85 95 92 88 90 85 88]
 [90 85 80 87 92 89 83 91 86 88]
 [85 88 82 89 94 86 91 88 84 87]]


In [51]:
score_mean = np.mean(score, axis=0)
print(score_mean)

[87.66666667 88.33333333 79.33333333 87.         93.66666667 89.
 87.33333333 89.66666667 85.         87.66666667]


In [52]:
score_var = np.var(score, axis=0)
print(score_var)

[ 4.22222222  8.22222222  6.22222222  2.66666667  1.55555556  6.
 10.88888889  1.55555556  0.66666667  0.22222222]


In [55]:
score_std = np.std(score, axis=0)
print(score_std)

[2.05480467 2.86744176 2.49443826 1.63299316 1.24721913 2.44948974
 3.29983165 1.24721913 0.81649658 0.47140452]


- **[5] Numpy: 정렬**

### **[실습 1] 1차원 배열 정렬**

<aside>
❓

다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.

</aside>

In [ ]:
arr = np.array([50, 10, 30, 40, 20])              # 배열 생성

arr = np.sort(arr)
print(arr)

[10 20 30 40 50]


In [58]:
arr = np.array([50, 10, 30, 40, 20])              # 배열 생성

arr = np.sort(arr)[::-1]
print(arr)

[50 40 30 20 10]


    ### [**실습 2] 2차원 배열 축 기준 정렬**
    
    <aside>
    ❓
    
    다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.
    
    </aside>

In [59]:
arr2d = np.array(                                 # 배열 생성
    [[8, 3, 5],
     [2, 9, 1]]
)

arr = np.sort(arr2d, axis=1)
print(arr)

[[3 5 8]
 [1 2 9]]


In [60]:
arr2d = np.array(                                 # 배열 생성
    [[8, 3, 5],
     [2, 9, 1]]
)

arr = np.sort(arr2d, axis=0)
print(arr)

[[2 3 1]
 [8 9 5]]


### **[실습 3] 인덱스를 반환하는 정렬**

<aside>
❓

다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.

</aside>

In [63]:
arr = np.array([15, 10, 20])  # 0 => 15, 1 => 10, 2 => 20

sorted_index = np.argsort(arr)[::-1]              # 인덱스 확인
print(sorted_index)                               # 인덱스 확인


[2 0 1]


In [64]:
sorted_arr = arr[sorted_index]                    # 인덱스 확인
print(sorted_arr)

[20 15 10]


- **[6] Numpy: 병합**
    
    ### **[실습 1] 1차원 배열 병합**
    
    <aside>
    💡
    
    다음 두 개의 1차원 배열을 `np.concatenate()`와 `np.hstack()`을 사용하여 병합하세요.
    
    </aside>

In [75]:
arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([4, 5, 6])                        # 배열 생성

merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)

[1 2 3 4 5 6]


In [76]:
merged_arr = np.hstack((arr1, arr2))
print(merged_arr)

[1 2 3 4 5 6]


    ### **[실습 2] 2차원 배열 병합**
    
    <aside>
    💡
    
    다음 두 개의 2차원 배열을 `np.concatenate()`와 `np.vstack()`을 사용하여 각각 병합하세요.
    
    </aside>

In [ ]:
arr1 = np.array(                                  # 배열 생성
    [[1, 2],
     [3, 4]]
)
arr2 = np.array(                                  # 배열 생성
    [[5, 6],
     [7, 8]]
)

merged_arr = np.concatenate((arr1, arr2), axis=0)
print(merged_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [78]:
merged_arr = np.vstack((arr1, arr2))
print(merged_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


다음 2개의 1차원 배열을 np.stack()을 사용하여 새로운 축을 따라 병합하세요.

In [79]:
arr1 = np.array([1, 2, 3])                        # 배열 생성
arr2 = np.array([4, 5, 6])                        # 배열 생성

stacked_arr = np.stack((arr1, arr2), axis=0)
print(stacked_arr)

[[1 2 3]
 [4 5 6]]


In [80]:
stacked_arr = np.stack((arr1, arr2), axis=1)
print(stacked_arr)

[[1 4]
 [2 5]
 [3 6]]


- **[7] Numpy 종합 실습**

<aside>
❓

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 전체 지점에서 과일별 총 판매량을 구하고, 가장 많이 판매된 과일을 찾는다.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
</aside>

In [4]:
import numpy as np

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([                           # 배열 생성
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])

In [107]:
# 1. 각 지점에서 6개월 동안 판매된 사과, 바나나, 오렌지의 월별 평균 판매량을 계산하세요.
print(sales_data.shape)  # (5, 3, 6)  => axis=0 5개 지점, axis=1 3개 과일, axis=2 6개월치 월별 데이터

avg_sales = np.mean(sales_data, axis=2)
print(avg_sales)

(5, 3, 6)
[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]


In [ ]:
# 2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
total_sales_per_month = np.sum(sales_data, axis=0)
print(total_sales_per_month)
print(total_sales_per_month.shape)                # 데이터의 크기(행, 열) 확인

max_sales_per_month = np.max(total_sales_per_month, axis=0)    # 각 월별 최대 판매량
max_sales_indicies = np.argmax(total_sales_per_month, axis=0)  # 최대 판매량이 기록된 과일 인덱스
print(max_sales_per_month)
print(max_sales_indicies)

fruits = np.array(['사과', '바나나', '오렌지'])           # 배열 생성
print(fruits[max_sales_indicies])


[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]]
(3, 6)
[520 620 750 860 760 830]
[0 0 0 0 0 0]
['사과' '사과' '사과' '사과' '사과' '사과']


3. 전체 지점에서 과일별 총 판매량을 구하고, 가장 많이 판매된 과일을 찾는다.

In [108]:
total_sales_per_fruit = np.sum(sales_data, axis = (0, 2))
print(total_sales_per_fruit)

fruits = np.array(['사과', '바나나', '오렌지'])           # 배열 생성
most_fruit = np.argmax(total_sales_per_fruit)
print(most_fruit)
print(fruits[most_fruit])

[4340 3515 3260]
0
사과


In [ ]:
# 4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
fruits = np.array(['사과', '바나나', '오렌지'])           # 배열 생성

mask = sales_data >= 150
locations = np.argwhere(mask)                     # 이름으로 데이터 선택
print(locations)                                  # 이름으로 데이터 선택

for loc in locations:                             # 이름으로 데이터 선택
    site, fruit, month = loc                      # 이름으로 데이터 선택
    print(f"지점 : {site+1}, 과일명 : {fruits[fruit]}, {month+1}월 : {sales_data[site, fruit, month]}")

[[0 0 1]
 [0 0 2]
 [0 0 3]
 [0 0 4]
 [0 0 5]
 [0 1 2]
 [0 1 3]
 [0 1 4]
 [0 1 5]
 [0 2 2]
 [0 2 5]
 [2 0 2]
 [2 0 3]
 [2 0 4]
 [2 0 5]
 [2 1 3]
 [2 1 5]
 [3 0 2]
 [3 0 3]
 [3 0 4]
 [3 0 5]]
지점 : 1, 과일명 : 사과, 2월 : 150
지점 : 1, 과일명 : 사과, 3월 : 200
지점 : 1, 과일명 : 사과, 4월 : 230
지점 : 1, 과일명 : 사과, 5월 : 180
지점 : 1, 과일명 : 사과, 6월 : 210
지점 : 1, 과일명 : 바나나, 3월 : 170
지점 : 1, 과일명 : 바나나, 4월 : 190
지점 : 1, 과일명 : 바나나, 5월 : 160
지점 : 1, 과일명 : 바나나, 6월 : 180
지점 : 1, 과일명 : 오렌지, 3월 : 160
지점 : 1, 과일명 : 오렌지, 6월 : 150
지점 : 3, 과일명 : 사과, 3월 : 160
지점 : 3, 과일명 : 사과, 4월 : 180
지점 : 3, 과일명 : 사과, 5월 : 170
지점 : 3, 과일명 : 사과, 6월 : 190
지점 : 3, 과일명 : 바나나, 4월 : 150
지점 : 3, 과일명 : 바나나, 6월 : 160
지점 : 4, 과일명 : 사과, 3월 : 150
지점 : 4, 과일명 : 사과, 4월 : 170
지점 : 4, 과일명 : 사과, 5월 : 160
지점 : 4, 과일명 : 사과, 6월 : 180


In [ ]:
# 여기에 코드를 작성해보세요!
