파이토치 시작

In [282]:
from IPython.display import HTML, display

display(HTML("""
<style>
.text-black { color: #000; }
.text-white { color: #fff; }

.text-gray-900 { color: #111827; }
.text-gray-700 { color: #374151; }
.text-gray-500 { color: #6b7280; }
.text-gray-300 { color: #d1d5db; }

.text-red-600 { color: #dc2626; }
.text-orange-600 { color: #ea580c; }
.text-yellow-600 { color: #ca8a04; }
.text-green-600 { color: #16a34a; }
.text-blue-600 { color: #2563eb; }
.text-indigo-600 { color: #4f46e5; }
.text-purple-600 { color: #9333ea; }
.text-pink-600 { color: #db2777; }
</style>
<div class="text-orange-600">
  안녕
</div>
"""))

In [283]:
import torch

In [284]:
a = torch.FloatTensor([[1,2],
                       [3,4]])
b = torch.FloatTensor([[1,2],
                       [1,2]])

print(a.size())
print(b.size())

print(a+b)
print(a-b)
print(a*b)
print(a/b)



torch.Size([2, 2])
torch.Size([2, 2])
tensor([[2., 4.],
        [4., 6.]])
tensor([[0., 0.],
        [2., 2.]])
tensor([[1., 4.],
        [3., 8.]])
tensor([[1., 1.],
        [3., 2.]])


In [285]:
c = torch.matmul(a,b)
c

tensor([[ 3.,  6.],
        [ 7., 14.]])

- 1D x 1D => 내적(dot product)
- 2D x 2D => 행렬 곱
- 3D x 3D => 배치 행렬 곱

### 파이토치 텐서값 할당

In [286]:
ft = torch.FloatTensor([[1,2],
                        [3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

- 딥러닝에서는 가중치, 출력값, 손실, 기울기 등을 모두 실수연산 해야한다.
- 정수형은 미분 불가 및 기울기 계산 불가하여 사용하지 않는다.
- 그래서 신경망 연산의 기본타입은 FloatTensor이다.

In [287]:
lt = torch.LongTensor([[1,2],
                       [3,4]])
lt

tensor([[1, 2],
        [3, 4]])

In [288]:
bt = torch.ByteTensor([[1,2],
                       [3,4]])
bt

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

과거에 mask 또는 조건필터링 용도로 사용했었음

In [289]:
mask = torch.BoolTensor([[1,2],
                         [3,4]])
mask

tensor([[True, True],
        [True, True]])

최근에는 BoolTensor로 사용하는 것이 표준

In [290]:
x = torch.FloatTensor(3,2)  # shape이 (3,2)인 텐서 생성
x

tensor([[-1.3963e+11,  1.8525e-42],
        [ 0.0000e+00,  2.2500e+00],
        [ 0.0000e+00,  2.5312e+00]])

In [291]:
torch.zeros(3,2)  # shape이 (3,2)이고 값이 0인 텐서 생성


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [292]:
torch.ones(3,2)  # shape이 (3,2)이고 값이 1인 텐서 생성


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [293]:
torch.randn(3,2)  # shape이 (3,2)이고 정규분포 난수값을 가진 텐서 생성


tensor([[ 0.5485, -0.1138],
        [ 1.2227,  0.5240],
        [ 1.4605,  0.6446]])

In [294]:
import numpy as np
x=np.array([[1,2],
            [3,4]])
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [295]:
x = torch.from_numpy(x) # Numpy ndarray를 Pytorch Tensor로 변환
print(x,type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [296]:
x = x.numpy() # Pytorch Tensor를 Numpy ndarray로 변환
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [297]:
ft.long()   # LongTensor 타입으로 변환. 소수점은 버림 

tensor([[1, 2],
        [3, 4]])

### 정수형으로 변환. 주로 분류 문제에서 정답 라벨에 사용한다.

In [298]:
lt.float()  # FloatTensor 타입으로 변환

tensor([[1., 2.],
        [3., 4.]])

#### 정수형 텐서를 연산, 학습용 입력으로 사용할때 
#### or 
#### 가중치 계산, 신경망 입력시에는 float형태로 입력한다. 

In [299]:
torch.FloatTensor([1,0]).byte() # ByteTensor로 변환

tensor([1, 0], dtype=torch.uint8)

In [300]:
torch.FloatTensor([1,0]).bool() # ByteTensor로 보다는 BoolTensor 사용

tensor([ True, False])

In [301]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       
                       [[5,6],
                        [7,8]],
                       
                       [[9,10],
                        [11,12]]]
) # 3개의 배치, 2행 2열
print(x.shape)  # numpy 스타일
print(x.size()) # pythorch 스타일

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


### 텐서의 차원수

In [302]:
print(x.dim())          # 텐서의 차원 수 출력
print(len(x.size()))    # 길이 -> 차원 수

3
3


### 특정 차원에 있는 요소 개수

In [303]:
print(x.size(1))          # 1번 축(axis=1)의 크기를 가져옴
print(x.shape[1])         # 1번 축(axis=1)의 크기를 가져옴

2
2


마지막 차원의 요소 개수

In [304]:
print(x.size(-1))          # 마지막 축의 크기를 가져옴
print(x.shape[-1])         # 마지막 축의 크기를 가져옴
print(x.size(2))           # 마지막 축의 크기를 가져옴
print(x.shape[2])          # 마지막 축의 크기를 가져옴

2
2
2
2


##### 텐서가 뭔지 알아봤습니다.

## 텐서 연산

In [305]:
a = torch.FloatTensor([[1,2],
                       [3,4]])
b = torch.FloatTensor([[2,2],
                       [3,3]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a==b)
print(a!=b)
print(a**b)
print()

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ 1.,  4.],
        [27., 64.]])



In [306]:
print(a)
print(a.mul(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])


In [307]:
print(a)
print(a.mul_(b))    # 제자리수행 _가 붙은 연산은 원본 Tensor를 직접 바꾼다. in-place
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


#### Sum, Mean (차원 축소 작업)


In [308]:
a = torch.FloatTensor([[1,2],
                       [3,4]])
print(x.size())

y = x.sum()        # 전체 합
print(y)
print(y.size())

z = x.mean()        # 전체 평균
print(z)
print(z.size())

torch.Size([3, 2, 2])
tensor(78.)
torch.Size([])
tensor(6.5000)
torch.Size([])


In [309]:
x = torch.FloatTensor([[1,2],
                       [3,4]])

print(x.sum(dim=0)) # 첫번째 차원(행) 방향으로 합산 (각 열의 합)
print(x.sum(dim=-1)) # 마지막 차원(행) 방향으로 합산 (각 행의 합)


tensor([4., 6.])
tensor([3., 7.])


x.sum(dim=0) : 행 축(dim=0)을 제거하면서 합산  
-> 행 축에 따라 값들을 더한다.  
-> 해당 축은 사라진다  
-> 남은것은 열 축  

x.sum(dim=-1) : 마지막 차원인 열 축(dim=-1)을 제거하면서 합산  
-> 남은 것은 행 축  

dim()은 기준 축 보다는 "제거할 축"  
연산 결과는 제거되지 않은 축 기준으로 해석

Broadcast : 텐서의 차원(크기) 가 다를 때, 연산을 위해 자동으로 차원을 확장해서 차원을 맞춰주는 기능


In [310]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [311]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


In [312]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
y = 1

print(x,x.size())

tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])


In [313]:
z = x + y
print(z, z.size())

tensor([[2., 3.],
        [4., 5.]]) torch.Size([2, 2])


```
y = 1 =>
[[1,1],
 [1,1]]
  => x와 동일한 shape으로 브로드캐스팅
```

In [314]:
x = torch.FloatTensor([[1,2],
                       [4,8]])
y = torch.FloatTensor([[3,5]])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([1, 2])


In [315]:
z = x + y
print(z)
print(z.size())


tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


y = [[3,5]] ->  
[[3,5],  
 [3,5]]  
x의 행수 만큼 복제

In [316]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [317]:
z = x + y
print(z)
print(z.size())


tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


x = (1 1 2)  
y =     (2)  
=> y = (1 1 2) 자동 확장  
y= [3,5] => [[[3,5]]]

In [318]:
x = torch.FloatTensor([[[2],
                        [8]]])        #
y = torch.FloatTensor([[3,2]])        #

print(x.size())
print(y.size())

print(x+y)

torch.Size([1, 2, 1])
torch.Size([1, 2])
tensor([[[ 5.,  4.],
         [11., 10.]]])


| 차원  | x    | y     | 호환여부            | 
|-------|------|-------|---------------------|
| -1차원| 2    | 3     | 다르고, 둘다 1 아님 |
|-2차원 | 2    | 3     | 다르고, 둘다 1아님  |
|-3차원 | 1    | -     | 자동 확장 가능      |

브로드캐스팅 조건 : 각 차원의 값이 같거나, 하나가 1일 경우에 자동 확장 가능  
=> -1, -2  차원의 shape이 맞지 않아 브로드캐스팅 실패  
가능하게 만들어주려면 차원이 맞거나, 어느 한쪽이 1이면 가능하다.

In [319]:
# reshape : 텐서 모양을 변경해준다.

x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       
                       [[5,6],
                        [7,8]],
                       
                       [[9,10],
                        [11,12]]]
)

print(x.size())

torch.Size([3, 2, 2])


In [320]:
print(x.reshape(12))
print(x.reshape(-1))


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


### reshape(-1)은 텐서를 1차원으로 펼칠 때 가장 자주 쓰는 방식이다.

In [321]:
print(x.reshape(3,4))       # 명시적으로 (3,4) 형태로 만든다.
print(x.reshape(3,-1))      # 3행은고정, -1은 자동계산  => 3 x ? = 12 -> ? = 4 => (3,4) 

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


```
reshape은 원소 갯수는 유지 
-1은 자동으로 계산해주는 자리표시자 
-1은 한 번만
```

In [322]:
print(x.reshape(3, 1, 4))     # 1행 4열짜리 행렬 3개
print(x.reshape(-1, 1, 4))    # 1행 4열짜리 행렬 3개

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [323]:
print(x.reshape(3,2,2,1))   # 2x2 행렬에 채널 1개를 붙인 데이터 3개

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


In [324]:
# tensor(
#     [
#         [[[1.], [2.]], 
#          [[3.], [4.]]],
        
#         [[[5.], [6.]], 
#          [[7.], [8.]]],
        
#         [[[9.], [10.]], 
#          [[11.], [12.]]],
#     ]
# )

```
reshape() 대신 view()를 사용할 수도 있다. 
view는 연속된 메모리 구조일 때만 사용한다.
reshape()은 내부적으로 필요하면 데이터복사도 수행하며 유연하게 작동하기 때문에 주로 사용한다.

squeeze() : 텐서에서 크기가 1인 차원만 제거한다. 
```

In [325]:
x = torch.FloatTensor([[[1,2],
                       [3,4]]])
# print(x.squeeze()) 
# print(x.squeeze().size()) 


squeeze() 함수는 크기가 1인 차원을 자동으로 제거해준다. 그래서 텐서의 차원을 줄여준다.
squeeze(dim) : dim에 설정한 특정 차원만 제거한다. 지정한 차원의 크기가 1일 경우에만 제거한다. 

In [326]:
print(x.squeeze(0).size())
print(x.squeeze(1).size())
print(x.squeeze(2).size())

torch.Size([2, 2])
torch.Size([1, 2, 2])
torch.Size([1, 2, 2])


unsqueeze() : 특정 위치에 새 차원을 추가한다.

In [327]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
print(x.unsqueeze(2))            # 2번 차원에 크기 1인 축 추가 (2, 2) -> (2, 2, 1)
print(x.unsqueeze(-1))           # 마지막 차원에 크기 1인 축 추가 (2, 2) -> (2, 2, 1)
print(x.reshape(2, 2, -1))     # 전체 원소수 유지 (2x2 = 4), -1 : 자동계산 => -> (2, 2, 1)
 


tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])


### 텐서 자르기 & 붙이기

In [328]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])

x.size()

torch.Size([3, 2, 2])

### 특정 차원에 접근

In [329]:
print(x[0])                 # 첫 번째 차원 (dim = 0) 접근
print(x[0, :])              # 첫 번째 차원으로 접근하고 그 다음 차원은 : 로 전체선택, 세번째 차원은 생략( 자동으로 전체선택)
print(x[0, :, :])           # 첫 번째 차원으로 접근하고, 


tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


뒷 차원의 : 은 생략가능하다 생락하면 자동으로 전체(:)로 처리된다.

In [330]:
print(x[-1])            # 첫 번째 차원에서 마지막 요소 선택. 나머지 차원은 자동선택
print(x[-1,:])            # 첫 번째 차원에서 마지막 요소 선택. 두번째 차원 전체선택. 세번째 차원은 생략 -> 자동선택
print(x[-1,:,:])            # 첫 번째 차원에서 마지막 요소 선택. 두번째, 세번째 차원은 전체 선택


tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


```
음수 인덱싱 -1은 마지막 요소를 의미한다.
뒤 차원의 : 는 생략해도 동일한 효과이다.
```

In [331]:
# 각 배치에서 첫번째 행만 가져온다.
print(x[:,0,:])

# 각 배치에서 첫번째 열만 가져온다.
print(x[:,:,0])


tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])


```
print(x[:,:,0].size()) = torch.size([3,2])
배치 수는 그대로 3유지
행차원 2 유지
열차원 선택되어 제거
범위로 접근하면 텐서의 차원수가 유지된다.
```

In [332]:
print(x[1:3, :, :].size()) # 배치 인덱스 1, 2번 선택. 나머지 차원은 전체 유지
print(x[:, :1, :].size())  # 모든 배치. 행에서 앞의 1개만 선택. 열은 전체 유지
print(x[:, -1, :].size()) # 모든 배치. 마지막 행을 제외한 전체 해. 열은 저체 유지


torch.Size([2, 2, 2])
torch.Size([3, 1, 2])
torch.Size([3, 2])


In [333]:
x = torch.zeros(10,4)
print(x)
splits = x.split(4,dim=0)   # 0번 차원(dim=0)을 따라 4개씩 잘라라 (반환값 : 튜플)
# splits
for s in splits:
    print(s.size())

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


chunk() : 텐서를 청크 수로 나눕니다.

In [334]:
x = torch.zeros(8,4)

chunks = x.chunk(3,dim=0)   # 0번 차원(dim=0)을 기준으로 3조각으로 나눈다.

for c in chunks :
    print(c.size()) 

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


```
split(size, dim): 기준은 크기. 마지막에 나머지 조각을 만든다.
chunk(n,dim) : 기준은 갯수, 최대한 균등하게 분할한다. (나머지 최소화)

index_select() : 차원 인덱스를 사용하여 요소를 선택한다.
```


In [335]:
x = torch.FloatTensor([[[1,1],
                        [2,2]],
                       
                       [[3,3],
                        [4,4]],
                       
                       [[5,5],
                        [6,6]]])      # size = 3,2,2
indice = torch.LongTensor([2,1])
                       
print(x.size())
print(indice.size())



torch.Size([3, 2, 2])
torch.Size([2])


In [336]:
y = x.index_select(dim=0, index=indice) # 0번 차원(dim=0)에서 indice에서 지정한 순서대로 선택
                                        # 먼저 x[2], 그 다음 x[1]
                                        
print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


```
index_select() 함수
순서가 유지됨 indice에서 설정한 [2,1] 순서 그대로 사용된다.
중복 인덱스도 가능하다.
결과 인덱스는 새로 생성된다 (원본  x가 변할일은 없다.)
index는 반듯이 LongTensor로 설정해야 한다.
```


In [337]:
# 중복 선택
x.index_select(0, torch.LongTensor([0, 0, 2]))


tensor([[[1., 1.],
         [2., 2.]],

        [[1., 1.],
         [2., 2.]],

        [[5., 5.],
         [6., 6.]]])

index_select(dim, index): 지정한 축에서 원하는 인덱스만 순서대로 선택하는 함수

cat() : 여러 텐서를 연결한다.

In [338]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
y = torch.FloatTensor([[10,11,12],
                       [13,14,15],
                       [16,17,18]])

print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [339]:
z = torch.cat([x,y],dim=0) # 0번 차원(행 방향)으로 이어 붙이기
print(z)
print(x.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([3, 3])


cat()의 규칙
붙이는 축을 제외한 나머지 차원은 반드시 동일
(행, 열) 기준일 때
dim = 0, -> 행 증가
dim = 1 ->  열 증가

In [340]:
z = torch.cat([x,y], dim=1)
# z = torch.cat([x,y], dim=-1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [343]:
z = torch.cat([x,y], dim=-1)
z

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])

```
torch.cat 함수는 지정한 축을 기준으로 텐서를 이어붙인다.
그외 차원은 모두 같아야한다.
```

```
torch.stack() 함수는 기존 텐서들을 이용해 새로운 차원으로 쌓는다.
x, y 각각의 shape (3,3)은 그대로 유지하면서 맨 앞에 새로운 차원 (dim=0)이 하나 생기게 된다.
```

| 함수 |  차원 변화  |          의미          |
|------|-------------|------------------------|
|cat   | 차원 수 동일| 기존 축으로 이어 붙임  |
|stack | 차원 +1     | 새로운 축을 만들어 쌓음|


In [341]:
print(torch.cat([x, y], dim=0).size())
print(torch.stack([x, y], dim=0).size())
z = torch.stack([x,y],dim=-1)

print(z)
print(z.size())

torch.Size([6, 3])
torch.Size([2, 3, 3])
tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


In [ ]:
print(torch.stack([x,y], dim=0).size()) # 맨 앞 차원 추가 (의미 : 텐서 묶음)
print(torch.stack([x,y], dim=-1).size()) # 맨 뒷 차원 추가 (의미 : feture/channel)

torch.Size([2, 3, 3])
torch.Size([3, 3, 2])


In [345]:
z = torch.stack([x,y],dim=0)

print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [363]:
torch.cat([(1,3,3),(1,3,3)],dim=0)

TypeError: expected Tensor as element 0 in argument 0, but got tuple

In [ ]:
# cat 함수와 unsqueeze 함수를 통해 같은 결과를 구현해 보세요. (1 3 3) + (1 3 3) = (2 3 3)

print(x.unsqueeze(0).size())
print(y.unsqueeze(0).size())


z = torch.cat([x.unsqueeze(0),y.unsqueeze(0)], dim=0)
print(z)
print(z.size())

torch.Size([1, 3, 3])
torch.Size([1, 3, 3])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


```
orch.cat([], dim=0) 방향으로 이어 붙임
변수.unsqueeze(dim) : 해당하는 dim 위치에 크기 1인 새 차원 추가
torch.cat([1,3,3],(1,3,3),dim=0) => (2,3,3)

반복문 결과를 하나로 병합하기
```

In [364]:
result = []
for i in range(5):
    x = torch.FloatTensor(2, 2) # shape이 (2, 2). 값이 초기화되지 않은 랜덤 메모리값
    result += [x]               # (2, 2) 텐서를 리스트에 하나씩 추가
    
result = torch.stack(result)    # 리스트에 들어있는 텐서들을 새로운 차원으로 쌓는다.
result.size()                   # (5,2,2)

torch.Size([5, 2, 2])

```
stack을 사용하려면 모든 텐서의 shape이 동일해야 한다.
for문을 통해 리스트 -> 텐서로 묶으면 깔끔하게 병합할 수 있다.
배치 데이터 생성할때 이러한 방식으로 많이 사용한다. 
```

### 유용한 메서드

expand() : 크기가 1인 차원을 지정한 크기만큼 확장해서, 같은 값이 반복된 것처럼 보이게 한다.
(메모리는 복사하지 않는다)

In [365]:
x = torch.FloatTensor([[[1,2]],
                       [[3,4]]]) # size 2,1,2
print(x.size())

torch.Size([2, 1, 2])


In [373]:
y = x.expand(2,3,2)   # 기존 shape : (2,1,2)-> 목표 shape : 2,3,2
                        # dim = 1 -> 3 으로 확장하고, 나머지 차원은 그대로 유지한다.
# y = x.expand(*[2,3,2]) # 같은의미임 (list 나 튜플 전달시에 unpacking해서 사용)

print(y)
print(y.size())


tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


```
expand는 값을 복사하지 않는다.
내부적으로 같은 메모리를 여러번 참조(메모리 효율이 좋다.)

expand() 함수는 크기 1인 차원을 복사없이 늘려서 확장시키는 연산이다.
```

In [376]:
# expand의 기능을 cat 함수를 이용해서 똑같이 구현해보세요.
z = torch.cat([x,x,x],dim=1)
print(z)
print(z.size())


tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


```
cat 함수는 실제 데이터를 복사. in-place 수정해도 안전
expand 함수는 메모리 공유. in-place 수정을 하면 공유된 메모리값이 바뀔 위험성이 있다.
```

In [377]:
print(x.expand(2,3,2).size())
print(torch.cat([x,x,x],dim=1).size())

torch.Size([2, 3, 2])
torch.Size([2, 3, 2])


```
shape은 같지만 메모리 복사 일어남 / 일어나지 않음 차이가 있다.
randperm(n) : 랜덤 순열 (0부터 n-1 까지의 정수를 무작위로 섞은 순열 텐서를 반환. 중복은 없다.)
```

In [380]:
x = torch.randperm(10)  # 0부터 9까지
x

tensor([2, 7, 4, 5, 0, 1, 3, 8, 6, 9])

### argmax() : 최대값의 인덱스를 반환한다.

In [381]:
x = torch.randperm(3**3).reshape(3,3,-1)    # 27개의 요소 => resahpe(3,3,?) => (3,3,3)
print(x)
print(x.size())

tensor([[[ 9, 11, 23],
         [ 6, 20, 21],
         [ 7, 24,  2]],

        [[ 8,  5,  1],
         [16, 10, 19],
         [ 3, 18, 13]],

        [[14, 12, 17],
         [ 0,  4, 26],
         [25, 15, 22]]])
torch.Size([3, 3, 3])


In [ ]:
y = x.argmax(dim=-1)    # 마지막 차원(열)에서 가장 큰 값의 인덱스를 반환하고, 설정한 차원은 삭제한다.
print(y)
print(y.size())

tensor([[2, 2, 1],
        [0, 2, 1],
        [2, 2, 0]])
torch.Size([3, 3])


```
argmax(dim=k) 는 k번 차원에서 하나를 선택하고, 그 해당 차원은 삭제한다.
만약 차원을 유지하고 싶다면 keepdim=True 옵션을 설정해준다.
```

In [384]:
y = x.argmax(dim=-1, keepdim=True)
print(y)
print(y.size())

tensor([[[2],
         [2],
         [1]],

        [[0],
         [2],
         [1]],

        [[2],
         [2],
         [0]]])
torch.Size([3, 3, 1])


```
topk() : 상위 k개의 값과 해당 인덱스를 튜플형태로 반환한다.
```

In [385]:
values, indices = torch.topk(x,k=1,dim=-1)  # 마지막차원에서 상위 1개(k=1)를 선택하여 값과 인덱스 반환

print(values)
print(values.size())

print(indices)
print(indices.size())

tensor([[[23],
         [21],
         [24]],

        [[ 8],
         [19],
         [18]],

        [[17],
         [26],
         [25]]])
torch.Size([3, 3, 1])
tensor([[[2],
         [2],
         [1]],

        [[0],
         [2],
         [1]],

        [[2],
         [2],
         [0]]])
torch.Size([3, 3, 1])


```
topk 옵션에 k=1로 하면 argmax + keepdim 옵션 사용과 결과가 같다.
k=1인 경우에도 topk는 차원을 줄이지 않는다.
```

In [386]:
# squeeze()
print(values.squeeze(-1))   # 마지막 차원 크기가 1이므로 제거
print(indices.squeeze(-1))   # 마지막 차원 크기가 1이므로 제거

tensor([[23, 21, 24],
        [ 8, 19, 18],
        [17, 26, 25]])
tensor([[2, 2, 1],
        [0, 2, 1],
        [2, 2, 0]])


In [387]:
_, indicies = torch.topk(x,k=2,dim=-1)
print(indices)
print(indices.size())
print(x.argmax(dim=-1) == indices[:,:,0])

tensor([[[2],
         [2],
         [1]],

        [[0],
         [2],
         [1]],

        [[2],
         [2],
         [0]]])
torch.Size([3, 3, 1])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


```
indices.size() = (3,3,2)
x.argmax(dim=-1) : 마지막 차원(열)의 각 위치의 최대값의 인덱스 -> shape : (3,3)
indices[:,:,0] : k가  2 인덱스 중에서 가장 큰 값의 인덱스만 선택 -> shape : (3,3)

topk(k,dim)는 기본적으로 내림차순 정렬
indices[...,0] : 최대값 위치
indices[...,1] : 두번째로 큰 값 위치

sort()를 사용해서 Topk 구현하기

```

In [1]:
import torch
x = torch.randperm(3**3).reshape(3, 3, -1)  # 27개의 요소 => reshape(3, 3, ?) => (3, 3, 3)
print(x)
print(x.size())

tensor([[[19, 14, 23],
         [ 6,  8, 18],
         [ 1, 24, 25]],

        [[10,  9, 21],
         [ 2, 12,  3],
         [11, 15, 17]],

        [[ 7,  5,  0],
         [13, 20, 26],
         [16, 22,  4]]])
torch.Size([3, 3, 3])


sort() : dim을 기준으로 정렬한다. 반환값은 (정렬된 값, 정렬 전 원래 index) 튜플

In [2]:
values, indices = torch.sort(x, dim=-1, descending=True)    # 마지막 차원(열)을 기준으로 내림차순 정렬

print(values)               # 정렬된 값
print(values.size())

print(indices)              # 정련전 원래 위치
print(indices.size())

tensor([[[23, 19, 14],
         [18,  8,  6],
         [25, 24,  1]],

        [[21, 10,  9],
         [12,  3,  2],
         [17, 15, 11]],

        [[ 7,  5,  0],
         [26, 20, 13],
         [22, 16,  4]]])
torch.Size([3, 3, 3])
tensor([[[2, 0, 1],
         [2, 1, 0],
         [2, 1, 0]],

        [[2, 0, 1],
         [1, 2, 0],
         [2, 1, 0]],

        [[0, 1, 2],
         [2, 1, 0],
         [1, 0, 2]]])
torch.Size([3, 3, 3])


In [20]:
x = values[:,:,0]
y = indices[:,:,0]

print(x.shape)
print(y.shape)


torch.Size([3, 3])
torch.Size([3, 3])


In [21]:
x = values[:,:,:1]
y = indices[:,:,:1]

print(x.shape)
print(y.shape)

print(x.squeeze(-1).size())
print(y.squeeze(-1).size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])
torch.Size([3, 3])
torch.Size([3, 3])


sort() + 슬라이싱 방식은 topk와 동일한 결과를 만들어 낼 수 있다.
그러나 상위 k개만 필요할 때는 topk를 쓰는것이 더 유용하다.

In [24]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)   # 0~8 요소를 가진 3x3(-1이 자동계산)의 2차원 텐서
print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [26]:
mask = x > 4
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [27]:
y = x.masked_fill(mask, value=-1)   # mask가 True인 위치만 -1로 채운다.

y

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

```
- 이런 패턴을 사용하는 경우
    - 이미지 padding 처리
    - loss 계산시에 무시할 값 처리
    - attention mask
이런 패턴에서 주로 사용을한다.
```

ones(), zeors() : 모든 요소가 1 또는 0으로 채워진 텐서를 생성한다.

In [28]:
print(torch.ones(2,3))
print(torch.ones(2,3).size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])


In [32]:
print(torch.zeros(2,3))
print(torch.zeros(2,3).size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [34]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])

print(x)
print(x.size())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [35]:
print(torch.ones_like(x))   # x와 동일한 shape, 동일한 dtype으로 모든 값을 1로 채운 텐서
print(torch.zeros_like(x))   # x와 동일한 shape, 동일한 dtype으로 모든 값을 0으로 채운 텐서

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


ones_like() ,zeros_like() 는 기준 텐서와 동일한 형태의 초기화 텐서를 만들 때 사용한다.