## Pytorch autograd (자동미분)

In [1]:
import torch

In [2]:
# 역전파를 위해서 x에 대한 gradient 계산 활성
x = torch.FloatTensor(
    [[1, 2],
     [3, 4]]
).requires_grad_(True)

requires_grad_(True): 이 텐서에 대해서 미분값을 구하겠다.  
일반적인 학습에서는 필요없지만 입력에 대한 기울기 분석시에 사용 

In [4]:
# 연산트리 자동 생성
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


grad_fn이 각 연산을 추적

In [5]:
# 자동 미분을 통한 역전파
y.backward() # 스칼라값 y를 기준으로 연결된 모든 텐서의 gradient를 자동으로 계산

In [6]:
# 역전파 이후 x에 대한 손실함수의 기울기(미분값) 확인
print(x.grad) # y에 대해 계산된 x위 gradient(∂y/∂x) 출력

tensor([[2., 4.],
        [6., 8.]])
